Riey/kime

Cargo.lock
xim/src/handler.rs

When IM give InputStyle::PREEDIT_CALLBACKS produce critical bugs I don't know why maybe we don't give some important parameter but I think on-the-spot need to removed it's not worth to contain :thinking: 
* Commit doesn't work
* It create IC every time it focused
* And never destory it

Fix java awt working

---

pkg/control.in

This fix works well on Ubuntu 20.04 LTS

Fixed lib names in control.in

---

README.ko.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md

- Fix some typoes
- Add Korean translation(`CONFIGURATION.ko.md`)
- Make default value easier to read

Improve the configuration guide

---

README.ko.md
README.md

Using country flag for languages probably isn't good idea. Especially, English is chosen for official language by many countries, [like 50+ countries](https://en.wikipedia.org/wiki/List_of_territorial_entities_where_English_is_an_official_language), and that makes impossible to choose a country flag for English. Also Korean has a same problem (although it's name is **Korea**n), like China (조선족; based on 문화어) and Russia (고려인; based on 고려말). And there's many constructed languages that don't represent any countries by design. These examples show we can't match languages and countries one by one.
Related: #141

Don't use country flag to represent languages

---

Cargo.lock
src/frontends/wayland/Cargo.toml
src/frontends/wayland/src/main.rs

TODOs
1. wayland앱에서 KeyRepeat시작
2. KeyRepeat인 상태로 포커스를 GTK앱이나 기타등 밖으로 탈출함
3. 파이어폭스에 repeat글자가 연타되고, 그거랑 GTK_IM의 입력이 같이 들어옴
Closes #139

Implement KeyRepeat to the Wayland frontent

---

src/frontends/wayland/src/main.rs

We must handle zero RepeatInfo.rate unless we'll get NaN due to floating point divide by zero.

wayland: Handle RepeatInfo event with zero rate

---

src/frontends/wayland/src/main.rs

With input-method-unstable-v2, it's impossible to finish preedit texts before deactivate.
> I think this is a bug in IME. Focus changes deactivates the input-method and I think there is no way to know it is going to be deactivated in advance. Which means IME does not have chance to commit string to old text-input. Also, by the protocol, there is no way to distinguish the text-input behind. With these, I think IME should reset their internal states (for example, to-be-committed string) on deactivate. This is what my wlchewing does, and so it does not have this bug.
>
> @xdavidwu
- https://github.com/swaywm/sway/pull/4932#issuecomment-774113129

wayland: Don't bother to commit preedit text on deactivate

---

docs/CHANGELOG.md
src/frontends/wayland/src/main.rs

Fixes the regression regarding key repeat introduced by #214
> IME를 껐다킨 직후엔 잘되는데 파이어폭스를 켜고 alt+1 alt+2 alt+1 로 탭을 바꿨다돌아오면 ㅋㅋㅋㅋ가 안되기 시작함

wayland: Don't forget RepeatInfo on deactivate

---

docs/CHANGELOG.md
src/engine/core/src/keycode.rs

Fix #291
Maybe it's better to use keysym because many users don't familiar with scancode mapping

Make keycode 130 to Hangul

---

src/engine/core/tests/sebeolsik_sin1995.rs

`sin1995` should not be able to compose multiple jungseong with left-hand only keys, because of its system.

Add more sin1995 compose jungseong test cases

---

docs/CHANGELOG.md
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs

Fix preedit string disapear when press hotkey

---

docs/CHANGELOG.md
src/engine/core/src/state.rs
src/engine/core/tests/dubeolsik.rs
src/engine/core/tests/sebeolsik_390.rs
src/engine/core/tests/sebeolsik_391.rs

Make character typing order strict `ㅏ + ㄱ = ㅏㄱ`

Make character typing order strict `ㅏ + ㄱ = ㅏㄱ`

---

Cargo.lock
Cargo.toml
src/engine/backend/src/lib.rs
src/engine/backends/hangul/Cargo.toml
src/engine/backends/hangul/src/lib.rs
src/engine/backends/hangul/src/state.rs
src/engine/backends/hanja/Cargo.toml
src/engine/backends/hanja/src/lib.rs
src/engine/backends/math/src/lib.rs
src/engine/core/Cargo.toml
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/src/os.rs
src/engine/core/tests/math.rs

Let `Hanja`, `Math` to InputMode this work as another layer of InputCategory
`InputMode` is life `InputEngine` but it can be turn off without hotkey if mode is disabled, then previous engine is continue work
and `set_mode` may failed like press `Hanja` when there is no preedit string or in latin engine

Make InputMode

---

docs/CHANGELOG.md
src/engine/core/src/config.rs

capi에서 설정 파일을 로딩하는데에는 `Config::load_from_config_dir` 이 사용됩니다. 근데 이 함수에서는 이번에 새로 바뀐 설정 파일 레이아웃을 따라가지 않고 예전 EngineConfig을 사용하고 있습니다. 그래서 새 설정 파일을 읽지 못하고 항상 default 설정을 가져옵니다.
이것을 고칩니다.
설정 파일을 xdg config에서 읽어서 설정을 만드는 코드가 여러 군데에 파편화되어있는데 이걸 한 군데로 합쳐서 이런 버그가 안 생기게 하면 좋을 것 같습니다

capi에서 설정 파일 로딩에 있는 버그를 고칩니다

---

src/engine/core/src/os.rs

global_category_state + kime-indicator 조합이 작동하지 않아서 뭔가 하고 봤더니 여기만 1 대신 b'1' 을 사용해서 혹시 이거 때문이 아닐지 싶네요 제 환경에서 빌드가 깨져서 테스트는 못 해봤습니다

Correct protocol of indlcator state

---

docs/CHANGELOG.md
src/engine/backends/hangul/data/sebeolsik-3sin-p2.yaml

Fix wrong mapping in sebeolsik-3sin-p2.
According to this [site](https://pat.im/1136), S-k should print `"`.
Since this PR only fixes a small problem, we don't need to update any documents.

Fix sebeolsik-3sin-p2 '"'

---

docs/CHANGELOG.md
src/engine/backends/hangul/src/state.rs
src/engine/core/tests/sebeolsik_3_90.rs
src/engine/core/tests/shared.rs

Fix choseong converted into jongseong even `TreatJongseongAsChoseong` is off

---

Cargo.lock
nix/deps.nix
shell.nix
src/engine/backend/Cargo.toml
src/engine/capi/src/lib.rs
src/engine/core/Cargo.toml
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/font.rs
src/tools/candidate-window/Cargo.toml
src/tools/candidate-window/src/main.rs
src/tools/check/Cargo.toml
src/tools/log/Cargo.toml

Replace fontconfig with fontdb
Collect font load stuff into core lib

Improve config control

---

docs/CHANGELOG.md
src/engine/backends/hangul/data/sebeolsik-3-91.yaml

세벌식 3-91 자판의 `S-Equal` 키에 `+` 대신 `>` 가 배치되어 있던 버그를 수정
세벌식 3-91 자판에 플러스 기호가 없던 버그를 고쳤습니다.
- [ X ] I have documented my changes properly to adequate places
- [ O ] I have updated the docs/CHANGELOG.md

Pr plus sign in 3 91

---

build-docker/ubuntu-21.04/Dockerfile

Fix build error with ubuntu-21.04 docker image.
I didn't test another images, so other docker images also could have same problem.

Fix build error with ubuntu-21.04 Docker

---

docs/CHANGELOG.md
src/tools/indicator/src/main.rs

Gnome extension for KSNI requires id, so this PR implements `KimeTray`'s `id` method.
- [v] I have documented my changes properly to adequate places
- [v] I have updated the docs/CHANGELOG.md

Fix issue kime icon is not shown on Gnome tray

---

docs/CHANGELOG.md
src/frontends/gtk2/src/immodule.c

Fix #562
Fix #563
Create new flag `is_committing` it checks whether reset event is real or dummy.

Fix firefox bugs

---

docs/CHANGELOG.md
src/engine/config/src/lib.rs
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/tools/check/src/main.rs

Added translation layer that allows using keyboards with non-QWERTY layoutse
close #586

add translation layer

---

.github/workflows/release.yaml

Ubuntu 22.04 release 추가 ( QT 5.15.3 )

Add QT 5.15.3 for ubuntu 22.04 support

---

docs/CHANGELOG.md
src/engine/backend/src/keycode.rs

The Linux "hardware codes" 77 and 78 *usually* point to X11 keycode `Num_Lock` and `Scroll_Lock` each. Common codes for F11 and F12 are 95 and 96.
I said *usually* because `.Xmodmap` could mess up all the keycodes in X11.
- [Code values on Linux (X11), in MDN](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values#code_values_on_linux_x11)
- `xmodmap -pke` on my computer

Fix scan code of F11 / F12

---

docs/CHANGELOG.md
res/default_config.yaml
scripts/control.in
src/engine/config/src/lib.rs
src/engine/core/src/config.rs

Fix #611 (need work for package side)
Alternative of #612
- Set default font to Noto Sans
- Make D2Coding to fallback font

Set default font to Noto Sans

---

docs/CHANGELOG.md
res/kime-xdg-autostart
res/kime.desktop
scripts/install.sh

This PR closes #576 by introducing a new shell script while fixing other various parts, such as icon name, of the `kime.desktop` autostart file.
* #576 was caused by `systemd-xdg-autostart-generator`, which KDE depends on since [5.21](https://invent.kde.org/plasma/plasma-workspace/-/commits/v5.21.0?search=systemd+startup), [skipping `.desktop` files with the entry `X-GNOME-Autostart-Phase`](https://man.archlinux.org/man/systemd-xdg-autostart-generator.8.en#DESCRIPTION).
* The user unit `app-kime@autostart` will load when we simply remove the line. However, since `kime` spawns a daemon and exits immediately, systemd will kill the `kime` process because of it exiting before the automatically generated unit's `TimeoutSec`.
* Since the `TimeoutSec` value is [hardcoded to be 5 …

Fix autostart

---

build-docker/ubuntu-22.10/Dockerfile
docs/CHANGELOG.md

https://github.com/Riey/kime/blob/develop/build-docker/ubuntu-22.04/Dockerfile as a reference.
Merged multiple apt-get install command into a one commend for smaller image and faster build.

Add dockerfile for ubuntu-22.10

---

src/engine/backends/hangul/src/layout.rs

Make `from_items` public, able to bypass YAML parsing

---

src/engine/core/Cargo.toml
src/engine/core/src/lib.rs

해당 mode들이 `cfg(unix)` 이외에서 컴파일되지 않는 `kime-engine-candidate` 의존성을 갖고 있어서, 이를 (임시방편?으로) 제외할 수 있게 feature로 빼두되 default features에는 넣어둡니다.
- 그러고 보니 [/docs/CONFIGURATION.md](https://github.com/Riey/kime/blob/0b772b8a5ed87347d3f75b28170db7fcf46c361e/docs/CONFIGURATION.md)에는 mode에 관해서 문서화가 되어 있지 않네요 (사실 써본 적도 없습니다 설정 제대로 안 되는 거 같기도 하고)
- wasm으로 kime 컴파일 굴려서 웹에서 사용해보고 있습니다 https://github.com/xnuk/kime-web-playground (https://kime.xnu.kr/)

kime-engine-core: Make hanja/math/emoji features optional

---

docs/CHANGELOG.md
src/frontends/wayland/src/main.rs

Fixes #663
> The serial number reflects the last state of the zwp_input_method_v2 object known to the client. The value of the serial argument must be equal to the **number of done events** already issued by that object. When the compositor receives a commit request with a serial different than the number of past done events, it must proceed as normal, except it should not change the current state of the zwp_input_method_v2 object.
https://wayland.app/protocols/input-method-unstable-v2#zwp_input_method_v2:request:commit
다른 곳 치우고 `ImEvent::Done`에서만 `serial`을 1씩 증가하게 바꾸니 일단은 작동하는 거 같습니다.
[wlroots/wlroots#4497](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4497)을 읽어봤더니, `current_serial`은 0부터 시작해서 `wlr_input_method_v2_send_done`에서 1씩 올리고, 이렇게 예측한 `current_serial`이 받은 …

Fix to work on wlroots>=0.17.1 by changing increasing order of `serial`

---

src/frontends/qt5/src/input_context.cc

- [Qt 5: `int QString::length() const`](https://doc.qt.io/qt-5/qstring.html#length)
- [Qt 6: `qsizetype QString::length() const`](https://doc.qt.io/qt-6/qstring.html#length)
So I think it needs to be add explicit casting. (Build error occurs in latest gcc)

Fix Qt6 build

---

README.ko.md
README.md

While doing due diligence for https://github.com/nixos/nixpkgs/issues/180654 I noticed this repository has documentation for enabling Kime on NixOS.
The fix for 180654 is a breaking change, so this PR updates the Kime documentation.
I haven't updated the changelog because this is a NixOS breaking change, and is documented in the NixOS breaking changes for release 24.11.
Existing non-NixOS users are unaffected, and existing NixOS users will be informed when they update to 24.11.
New users in both cases are unaffected.

Update documentation for nixpkgs breaking change

---

Cargo.lock
docs/CHANGELOG.md
src/engine/core/tests/emoji.rs
src/engine/dict/Cargo.toml
src/engine/dict/build.rs
src/engine/dict/data/en.xml
src/engine/dict/data/ko.xml

Update unicode cldr
