src/handler.rs
src/handler/pe_window.rs
src/main.rs

Rework preedit window

---

src/engine/state.rs
src/handler.rs
src/handler/pe_window.rs

Apply spot_location

---

engine/src/characters.rs
engine/src/dubeolsik.rs
engine/src/state.rs

Complete jungseong

---

engine/src/dubeolsik.rs
engine/src/lib.rs

Support ESC

---

gtk3/src/lib.rs

Skip when ctrl pressed

---

gtk3/src/lib.rs

Change gtk cursor style

---

engine/src/dubeolsik.rs
engine/src/state.rs

Fix typing choseong bug

---

engine/src/characters.rs
gtk3/src/lib.rs

Reset when ctrl pressed

---

engine/src/lib.rs
engine/tests/dubeolsik.rs

Reset state when other keysym input

---

gtk3/src/lib.rs

Send preedit start, end signal

---

gtk3/src/lib.rs

Fix preedit signal emit order

---

engine/src/keycode.rs
engine/tests/dubeolsik.rs
gtk3/src/lib.rs

Fix firefox enter key doesn't work when preedit_end

---

gtk3/src/lib.rs

Fix many bugs in firerfox and vscode

Send key_event when key bypass with preedit_end

---

xim/src/handler.rs

[XIM] Reset when unset focus

---

engine/src/config.rs
engine/src/keycode.rs

Use DEFAULT_HANGUL_KEYS for make Default RawConfig

---

engine/data/config.yaml
engine/src/keycode.rs
gtk3/src/lib.rs
xim/src/handler.rs

Support control modifier

---

engine/data/config.yaml
engine/src/keycode.rs
gtk3/src/lib.rs
xim/src/handler.rs

Add Super modifier

---

CONFIGURATION.md
engine-cffi/src/lib.rs
engine/src/characters.rs
engine/src/config.rs
engine/src/lib.rs
engine/src/state.rs
engine/src/tests/dubeolsik.rs
engine/src/tests/sebeolsik_390.rs

Add more compose configs

---

CHANGELOG.md
Cargo.lock
engine-cffi/Cargo.toml
engine/Cargo.toml
engine/src/lib.rs
gtk3/Cargo.toml
xim/Cargo.toml

Fix unhandled keycode doesn't occur reset

---

engine/core/src/config.rs
engine/core/src/lib.rs
engine/core/tests/dubeolsik.rs
engine/core/tests/sebeolsik_390.rs
engine/core/tests/sebeolsik_391.rs
release.sh

Embed common used layouts

---

Cargo.lock
engine/capi/Cargo.toml
gtk3/Cargo.toml
xim/Cargo.toml
xim/src/handler.rs

Packaging into deb

---

gtk3/src/lib.rs

Fix super key bug

---

Cargo.lock
engine/capi/Cargo.toml
engine/capi/build.rs
engine/capi/data/config.yaml
engine/core/src/config.rs
engine/core/src/keycode.rs
pkg/release-7z.sh

Config rework

---

CHANGELOG.md
engine/cffi/src/lib.rs
gtk3/src/lib.rs
xim/src/handler.rs
xim/src/pe_window.rs

Update preedit_window when set_ic_values enter

---

CHANGELOG.md
xim/src/main.rs

Print version when --version args enter

---

gtk3/src/lib.rs
xim/src/handler.rs

Don't skip LOCK_MASK

---

engine/cffi/src/lib.rs
gtk3/src/lib.rs
xim/src/handler.rs

Don't skip numlock

---

CHANGELOG.md
CONFIGURATION.md
engine/capi/cbindgen.toml
engine/capi/data/config.yaml
engine/capi/src/lib.rs
engine/cffi/generate_bindings.sh
engine/cffi/kime_engine.h
engine/cffi/src/ffi.rs
engine/cffi/src/lib.rs
engine/core/src/config.rs
xim/src/handler.rs
xim/src/pe_window.rs

Add xim font size option

---

gtk3/src/lib.rs

there was a typo in an if statement

Fix preedit attributes

---

qt5/src/input_context.cc

[Qt] Don't commit ch when NULL

---

.github/workflows/ci.yaml
.vscode/launch.json
Cargo.lock
Cargo.toml
README.md
docs/CHANGELOG.md
wayland/Cargo.toml
wayland/src/main.rs
xim/src/main.rs
xtask/Cargo.toml
xtask/src/main.rs

Add wayland frontend

---

docs/CONFIGURATION.md

**[Click](https://github.com/simnalamburt/kime/blob/doc/docs/CONFIGURATION.md)** to see rendered CONFIGURATION.md

Make CONFIGURATION.md more newbie friendly

---

docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md

Don't use country flag to represent languages in CONFIGURATION.md

---

src/frontends/wayland/src/main.rs

Fix wayland input bug

---

.vscode/settings.json
Cargo.lock
docs/CHANGELOG.md
src/daemon/kimed/Cargo.toml
src/daemon/kimed/src/main.rs
src/frontends/wayland/Cargo.toml
src/frontends/wayland/src/main.rs
src/frontends/xim/Cargo.toml
src/frontends/xim/src/main.rs
src/version/Cargo.toml
src/version/build.rs
src/version/src/lib.rs

Set versioning

---

Cargo.lock
docs/CHANGELOG.md
src/frontends/xim/src/main.rs

Support all locales

---

.gitignore
docs/CHANGELOG.md
src/engine/cffi/src/lib.rs
src/engine/core/src/keycode.rs
src/frontends/gtk2/src/immodule.c
src/frontends/qt5/src/input_context.cc
src/frontends/qt5/src/input_context.hpp
src/frontends/qt5/src/plugin.hpp
src/frontends/wayland/src/main.rs
src/frontends/xim/src/handler.rs
src/xtask/src/main.rs

Support alt modifier

---

.github/workflows/ci.yaml
Cargo.lock
src/engine/cffi/Cargo.toml
src/engine/cffi/build.rs

Prevent output filename collision warnig which build engine twice caused by cbindgen

Use cbindgen as command

---

docs/CHANGELOG.md
src/frontends/wayland/src/main.rs

Wayland keymap fd close

---

.github/workflows/release.yaml
ci/build_release.sh
docs/CHANGELOG.md

Change release .tar.xz

---

src/frontends/wayland/src/main.rs

Key repeat of bypassed key shouldn't be handled by IME.
NOTE: This PR does **NOT** clo<b></b>ses https://github.com/Riey/kime/issues/207
- https://github.com/swaywm/sway/pull/4932#issuecomment-774113129
- https://github.com/korean-input/issues/issues/7

Fix unwanted key repeat bug on wayland

---

docs/CONFIGURATION.md

CONFIGURATION.md: Replace Korean word

---

.github/workflows/ci.yaml
Cargo.lock
src/engine/cffi/Cargo.toml
src/engine/cffi/build.rs

Set kime-engine-capi to dependencies
Rollback cbindgen as build-dependencies again

Fix engine build

---

src/engine/capi/Cargo.toml
src/engine/capi/src/lib.rs
src/engine/core/src/input_result.rs

Make capi no-panic

---

docs/CHANGELOG.md
src/frontends/wayland/src/main.rs

Let grab keyboard forever

---

.github/pull_request_template.md
.markdownlint.json

Create a simple pull request template
Markdownlint is rather annoying

Create a simple pull request template

---

src/engine/capi/cbindgen.toml
src/engine/capi/src/lib.rs
src/engine/cffi/src/lib.rs
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs
src/engine/core/tests/sebeolsik_390.rs
src/engine/core/tests/sebeolsik_391.rs
src/frontends/wayland/src/main.rs
src/frontends/xim/src/main.rs

* Add `kime_engine_set_hangul_enable`
* Add `kime_config_default`

Add some engine capis

---

README.ko.md
README.md

Add mention to performance in README

Add mention to performance in README

---

docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
res/default_config.yaml
src/engine/capi/cbindgen-c.toml
src/engine/cffi/benches/call_key.rs
src/engine/cffi/kime_engine.h
src/engine/cffi/kime_engine.hpp
src/engine/cffi/src/ffi.rs
src/engine/cffi/src/lib.rs
src/engine/core/examples/print_default_config.rs
src/engine/core/src/config.rs
src/engine/core/src/input_result.rs
src/engine/core/src/keycode.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs
src/frontends/gtk2/src/immodule.c
src/frontends/qt5/src/input_context.cc
src/frontends/wayland/src/main.rs
src/frontends/xim/src/handler.rs

Fix #223
This will break backward compatibility for config

Implement engine hotkeys

---

src/engine/cffi/Cargo.toml
src/engine/cffi/benches/call_key.rs

Ignore bench in stable toolchain

---

scripts/build.sh

Ignore strip output

---

.vscode/launch.json
.vscode/tasks.json
Cargo.lock
docs/CHANGELOG.md
src/frontends/gtk2/src/immodule.c

Reset doesn't commit its preedit char
Maybe releated #233

Fix gtk reset

---

docs/CHANGELOG.md
src/CMakeLists.txt
src/frontends/gtk2/src/immodule.c

Close #233
I don't know why gtk bench act different only I know is that kime call key_press function every time although it return `TRUE` :thinking: 
but it's worth to close issue because other apps work good

Refactor GTK

---

scripts/install.sh

Install script failed when file not exists

Fix install script

---

.vscode/launch.json
docs/CHANGELOG.md
src/frontends/xim/src/handler.rs

Fix xim event mask

---

.vscode/launch.json
docs/CHANGELOG.md
scripts/install.sh
src/frontends/xim/src/handler.rs

* Fix xim doesn't work [#246](https://github.com/Riey/kime/issues/246)

Release 1.0.1

---

.github/workflows/ci.yaml
Cargo.lock
deny.toml
src/daemon/indicator/Cargo.toml
src/frontends/wayland/Cargo.toml
src/version/Cargo.toml

Using cargo deny in CI

---

docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
scripts/install.sh

Fix global config path

---

.github/workflows/ci.yaml
Cargo.lock
deny.toml
docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
scripts/install.sh
src/daemon/indicator/Cargo.toml
src/frontends/wayland/Cargo.toml
src/version/Cargo.toml

* Fix xim freeze when typing fast [#251](https://github.com/Riey/kime/issues/251)
* Fix global config path [#252](https://github.com/Riey/kime/issues/252)

Release 1.0.2

---

Cargo.lock
docs/CHANGELOG.md
src/frontends/xim/src/handler.rs

Rollback #247

---

.github/workflows/release.yaml
Cargo.lock
build-docker/arch/Dockerfile
ci/build_deb.sh
docs/CHANGELOG.md
scripts/build.sh
scripts/install.sh
src/frontends/xim/src/handler.rs

* Rollback [#247](https://github.com/Riey/kime/issues/247)

Release 1.0.3

---

Cargo.lock
Cargo.toml
docs/CHANGELOG.md
src/daemon/indicator/Cargo.toml
src/daemon/indicator/src/main.rs
src/engine/capi/Cargo.toml
src/engine/capi/cbindgen-c.toml
src/engine/capi/cbindgen-cpp.toml
src/engine/capi/src/lib.rs
src/engine/cffi/kime_engine.h
src/engine/cffi/kime_engine.hpp
src/engine/cffi/src/ffi.rs
src/engine/cffi/src/lib.rs
src/engine/core/Cargo.toml
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/frontends/gtk2/src/gtk.c
src/frontends/gtk2/src/immodule.c
src/frontends/gtk2/src/immodule.h
src/frontends/qt5/src/plugin.cc
src/frontends/wayland/Cargo.toml
src/frontends/wayland/src/main.rs
src/frontends/xim/Cargo.toml
src/frontends/xim/src/main.rs
src/log/Cargo.toml
src/log/src/lib.rs

Improve logging

---

docs/CHANGELOG.md
src/engine/core/src/state.rs
src/engine/core/tests/sebeolsik_390.rs

Fix #263
Another reported issue can be fixed after #264 implemented

Fix choseong compose bug

---

src/frontends/gtk2/src/gtk.c
src/frontends/gtk4/src/gtk4.c
src/frontends/qt5/src/plugin.cc

Turn on logger for all frontends

Enable logger on gtk, qt

---

.vscode/launch.json
docs/CHANGELOG.md
src/daemon/indicator/src/main.rs

Fix indicator can't load icon data

---

Cargo.lock
build-docker/debian-buster/Dockerfile
docs/CHANGELOG.md
src/engine/core/Cargo.toml
src/frontends/xim/Cargo.toml

Add debian-buster docker

---

build-docker/ubuntu-18.04/Dockerfile
docs/CHANGELOG.md
src/CMakeLists.txt

Add Ubuntu 18.04 docker

---

.vscode/launch.json
.vscode/settings.json
docs/CHANGELOG.md
src/frontends/gtk2/src/immodule.c
src/frontends/gtk2/src/immodule.h
src/frontends/qt5/src/input_context.cc

Fix #280
Fix #282 
I can't find method for XIM, wayland so it just applys gtk, qt
and it gtk4 isn't implemented but I think it doesn't have this issue

Detect mouse click

---

.github/workflows/release.yaml
README.ko.md
README.md
docs/CHANGELOG.md

Release qt6

---

docs/CHANGELOG.md
src/engine/core/src/state.rs
src/engine/core/tests/sebeolsik_sin1995.rs

Fix this comment https://github.com/Riey/kime/issues/222#issuecomment-784566931

Fix cho-jung

---

src/engine/core/src/state.rs
src/engine/core/tests/dubeolsik.rs
src/engine/core/tests/sebeolsik_390.rs
src/engine/core/tests/sebeolsik_391.rs
src/engine/core/tests/sebeolsik_sin1995.rs

Move compose_jung state into CharacterState

Move compose_jung state into CharacterState

---

docs/CHANGELOG.md
src/engine/core/src/state.rs

Fix composable jungseong bug
This will pass #300 test cases

Fix composable jungseong bug

---

docs/CHANGELOG.md
src/frontends/wayland/src/main.rs
src/frontends/xim/src/handler.rs

Fix xim bug

---

.vscode/launch.json
docs/CHANGELOG.md
src/tools/check/src/main.rs

Fix kime-check fail

---

LICENSE

Correct copyright

---

LICENSE
NOTICE

Move copyright to notice

---

docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
res/default_config.yaml
src/engine/core/src/config.rs
src/engine/core/src/state.rs
src/engine/core/tests/sebeolsik_390.rs

Add `TreatJongseongAsChoseong` addon

Add TreatJongseongAsChoseong addon

---

docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/src/state.rs
src/engine/core/tests/dubeolsik.rs

Resolve #318
Add `FlexibleComposeOrder` addon

Add `FlexibleComposeOrder` addon

---

Cargo.lock
docs/CHANGELOG.md
src/tools/check/Cargo.toml
src/tools/check/src/main.rs

Check LANG env in kime-check

---

docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs

Add Commit hotkey

---

.github/workflows/release.yaml
docs/CHANGELOG.md
src/frontends/gtk2/src/immodule.c

Fix gtk preedit bug

---

.github/workflows/release.yaml
README.ko.md
docs/CHANGELOG.md
docs/CONFIGURATION.md
res/default_config.yaml
src/engine/core/src/config.rs
src/engine/core/src/keycode.rs
src/engine/core/src/lib.rs
src/engine/core/src/state.rs

Support emoji, hanja input

---

README.ko.md
README.md
docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
res/kime-wayland.desktop
res/kime-window.desktop
res/kime-xim.desktop
scripts/build.sh
scripts/install.sh

Fix #329 
Add desktop files
systemd service file is very hard to deal with graphic session so I make it as desktop file then user can make it autostart via DE

Add desktop files

---

docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
src/engine/core/src/config.rs
src/engine/core/src/state.rs
src/engine/core/tests/dubeolsik.rs

Fix #332
Add `TreatJongseongAsChoseongCompose` addon

Add `TreatJongseongAsChoseongCompose` addon

---

src/engine/capi/src/lib.rs
src/engine/cffi/benches/call_key.rs
src/engine/core/Cargo.toml
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/src/os.rs
src/engine/core/tests/shared.rs

Make engine portable
It's need for wasm(#196) or macOS, windows

Make engine portable

---

src/engine/core/src/config.rs
src/engine/core/src/lib.rs

Export builtin layouts

---

.vscode/launch.json
docs/CHANGELOG.md
src/frontends/gtk2/src/immodule.c
src/frontends/wayland/src/main.rs

Don't commit zero size string

---

docs/CHANGELOG.md
src/frontends/gtk2/src/immodule.c
src/frontends/gtk2/src/immodule.h

Prevent double key press

---

src/frontends/gtk2/src/immodule.c

Remove gtk_put_event

---

docs/CHANGELOG.md
src/frontends/gtk2/src/immodule.c

Revert #348
Enter doesn't work when preedit ended

Revert #348

---

.gitignore
docs/CHANGELOG.md
src/frontends/gtk2/src/immodule.c

For workarounding wayland and gtk4

Using signal connect client's window instead of gdk_window_add_filter

---

.vscode/settings.json
Cargo.lock
Cargo.toml
docs/CHANGELOG.md
src/engine/core/Cargo.toml
src/engine/core/src/os.rs
src/engine/dict/Cargo.toml
src/engine/dict/build.rs
src/engine/dict/src/lib.rs

Embed hanja dict, using rofimoji

---

README.ko.md
README.md
build-docker/debian-buster/Dockerfile
build-docker/ubuntu-18.04/Dockerfile
build-docker/ubuntu-20.04/Dockerfile
ci/build_deb.sh
docs/CHANGELOG.md
scripts/build.sh
scripts/control.in
scripts/release-deb.sh

Support build/crossbuild see #148

Support multiple archtectures

---

.github/workflows/release.yaml
Cargo.lock
Cargo.toml
README.ko.md
README.md
build-docker/arch/Dockerfile
build-docker/debian-buster/Dockerfile
build-docker/ubuntu-18.04/Dockerfile
build-docker/ubuntu-20.04/Dockerfile
deny.toml
docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
res/default_config.yaml
scripts/build.sh
scripts/install.sh
src/engine/cffi/Cargo.toml
src/engine/core/Cargo.toml
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/src/os.rs
src/frontends/wayland/Cargo.toml
src/frontends/wayland/src/main.rs
src/frontends/xim/Cargo.toml
src/frontends/xim/src/main.rs
src/tools/indicator/Cargo.toml
src/tools/indicator/src/main.rs
src/tools/run_dir/Cargo.toml
src/tools/run_dir/src/lib.rs
src/tools/version/src/lib.rs

Replace `libappindicator` to `ksni`
Boost compile speed (don't need to compile gtk, gio, appindicator) and cleaning codes

Integrate indicator

---

Cargo.lock
src/engine/dict/Cargo.toml
src/engine/dict/build.rs
src/engine/dict/src/lib.rs

Remove phf

---

Cargo.lock
docs/CHANGELOG.md
src/engine/backend/src/keycode.rs
src/engine/backends/hangul/Cargo.toml
src/engine/backends/hangul/src/lib.rs
src/engine/backends/hangul/src/state.rs
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/src/os.rs
src/engine/core/tests/hanja.rs
src/engine/dict/src/lib.rs

Let select hanja in preedit string

---

Cargo.lock
Cargo.toml
docs/CHANGELOG.md
res/default_config.yaml
src/engine/backends/emoji/Cargo.toml
src/engine/backends/emoji/src/lib.rs
src/engine/backends/hangul/src/lib.rs
src/engine/backends/hanja/src/lib.rs
src/engine/backends/latin/data/colemak.yaml
src/engine/backends/latin/data/dvorak.yaml
src/engine/backends/latin/data/qwerty.yaml
src/engine/core/Cargo.toml
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/src/os.rs
src/engine/core/tests/emoji.rs
src/engine/dict/Cargo.toml
src/engine/dict/build.rs
src/engine/dict/data/en.xml
src/engine/dict/data/ko.xml
src/engine/dict/src/lib.rs

https://user-images.githubusercontent.com/14910534/111523310-7ad08300-879e-11eb-982f-883bcef8edd7.mp4
Now sleep forever is not possible cause other than global input state is not blocking and global input state has 2 seconds timeout

Implement emoji mode

---

docs/CHANGELOG.md
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs

Fix arrow key bug in hangul

---

docs/CHANGELOG.md

* Make more key to commit hangul [#373](https://github.com/Riey/kime/issues/373)

Release 2.0.1

---

docs/CHANGELOG.md
src/engine/core/src/lib.rs
src/engine/core/tests/math.rs

Let Esc exit math mode

---

docs/CHANGELOG.md
src/engine/cffi/benches/call_key.rs
src/engine/core/src/lib.rs
src/engine/core/tests/hanja.rs

Fix can't select hanja

---

src/engine/dict/data/symbol_map.json

add more math symbols

---

docs/CHANGELOG.md
scripts/im_kime.rc

Terminate previous servers

---

docs/CHANGELOG.md
src/frontends/wayland/src/main.rs
src/tools/indicator/src/main.rs

Terminate previous indicator

---

docs/CHANGELOG.md
res/default_config.yaml
src/engine/backend/src/keycode.rs
src/engine/core/src/config.rs

Set `Default`, `Insert` key commit

Set delete, insert hotkey

---

docs/CHANGELOG.md
src/engine/cffi/src/lib.rs
src/tools/check/src/main.rs

Fix kime check failed

---

docs/CHANGELOG.md
res/default_config.yaml
scripts/im_kime.rc
src/engine/backend/src/keycode.rs
src/engine/cffi/src/lib.rs
src/engine/core/src/config.rs
src/engine/dict/data/symbol_map.json
src/frontends/wayland/src/main.rs
src/tools/check/src/main.rs
src/tools/indicator/src/main.rs

* Add more math symbol data [#385](https://github.com/Riey/kime/issues/385)
* Terminate previous servers in deb [#387](https://github.com/Riey/kime/issues/387)
* kime-indicator terminate previous process
* Set `Default`, `Insert` key commit
* Fix kime-check failed

Release 2.1.1

---

docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
res/default_config.yaml
src/engine/backends/emoji/src/lib.rs
src/engine/backends/latin/data/colemak.yaml
src/engine/backends/latin/data/dvorak.yaml
src/engine/backends/latin/data/qwerty.yaml
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs

Fix some shortcut bug
User config file must updated if not, shift key don't work properly

Make unhandled key `Commit` and `Bypass`

---

.gitignore
docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
res/default_config.yaml
src/engine/backend/Cargo.toml
src/engine/backend/src/keycode.rs
src/engine/backend/src/keymap.rs
src/engine/backend/src/lib.rs
src/engine/backends/emoji/src/lib.rs
src/engine/backends/hangul/src/characters.rs
src/engine/backends/hangul/src/layout.rs
src/engine/backends/hangul/src/lib.rs
src/engine/backends/hangul/src/state.rs
src/engine/backends/hanja/src/lib.rs
src/engine/backends/latin/data/colemak.yaml
src/engine/backends/latin/data/dvorak.yaml
src/engine/backends/latin/data/qwerty.yaml
src/engine/backends/latin/src/lib.rs
src/engine/backends/math/src/lib.rs
src/engine/cffi/Cargo.toml
src/engine/core/Cargo.toml
src/engine/core/benches/call_key.rs
src/engine/core/examples/print_type_sizes.rs
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs

* Make unhandled key `Commit` and `Bypass`
* Add `Ignore` hotkey behaviour
* Optimize Layout
* New `array-keymap` optional feature that super fast but take more memory

Release 2.1.2

---

docs/CHANGELOG.md
res/default_config.yaml
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs
src/frontends/gtk2/src/immodule.c

Ignore shift key input

---

Cargo.lock
docs/CHANGELOG.md
res/default_config.yaml
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs
src/frontends/gtk2/src/immodule.c

* Fix shift input error [#396](https://github.com/Riey/kime/issues/396)

Release 2.1.3

---

Cargo.lock
src/engine/core/Cargo.toml
src/engine/core/tests/hanja.rs
src/engine/core/tests/shared.rs
src/engine/dict/build.rs
src/engine/dict/src/lib.rs

Try prevent hanja panic

---

Cargo.lock
docs/CHANGELOG.md
src/engine/backend/Cargo.toml
src/engine/backend/src/keycode.rs
src/engine/backend/src/keymap.rs
src/engine/backends/emoji/src/lib.rs
src/engine/backends/hangul/src/layout.rs
src/engine/backends/hangul/src/state.rs
src/engine/backends/latin/src/lib.rs
src/engine/backends/math/src/lib.rs
src/engine/capi/Cargo.toml
src/engine/capi/src/lib.rs
src/engine/core/Cargo.toml
src/engine/core/benches/call_key.rs
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/emoji.rs
src/engine/core/tests/math.rs

Improve keymap

---

Cargo.lock
docs/CHANGELOG.md
src/engine/backend/Cargo.toml
src/engine/backend/src/keycode.rs
src/engine/backend/src/keymap.rs
src/engine/backends/emoji/src/lib.rs
src/engine/backends/hangul/src/layout.rs
src/engine/backends/hangul/src/state.rs
src/engine/backends/latin/src/lib.rs
src/engine/backends/math/src/lib.rs
src/engine/capi/Cargo.toml
src/engine/capi/src/lib.rs
src/engine/core/Cargo.toml
src/engine/core/benches/call_key.rs
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/emoji.rs
src/engine/core/tests/math.rs

* Improve keymap lookup speed +50%

Release 2.1.5

---

Cargo.lock
docs/CHANGELOG.md
src/frontends/xim/Cargo.toml
src/frontends/xim/src/handler.rs

Support preedit in xim

---

Cargo.lock
docs/CHANGELOG.md
src/frontends/xim/Cargo.toml
src/frontends/xim/src/handler.rs

* Support preedit string for XIM [#401](https://github.com/Riey/kime/issues/401)

Release 2.2.0

---

docs/CHANGELOG.md
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs

Bypass shift key

---

docs/CHANGELOG.md
src/engine/backends/latin/src/lib.rs
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs
src/engine/core/tests/latin.rs
src/engine/core/tests/math.rs
src/frontends/qt5/src/input_context.cc
src/frontends/qt5/src/input_context.hpp

Fix qt preedit handling

---

docs/CHANGELOG.md
src/engine/backends/latin/src/lib.rs
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs
src/engine/core/tests/latin.rs
src/engine/core/tests/math.rs
src/frontends/qt5/src/input_context.cc
src/frontends/qt5/src/input_context.hpp

* Rollback `preferred_direct` config
* Fix qt preedit handling [#425](https://github.com/Riey/kime/issues/425)

Release v2.3.2

---

scripts/build.sh
shell.nix

Add shell.nix

---

.gitignore
default.nix
docs/CHANGELOG.md
scripts/build.sh
scripts/install.sh
scripts/release-deb.sh
scripts/release-zst.sh
scripts/tool.sh
shell.nix

Support nix default

---

default.nix
shell.nix

Use unstable nixpkgs

---

.gitignore
default.nix
docs/CHANGELOG.md
res/default_config.yaml
scripts/build.sh
scripts/install.sh
scripts/release-deb.sh
scripts/release-zst.sh
scripts/tool.sh
shell.nix
src/engine/backends/latin/src/lib.rs
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/engine/core/tests/dubeolsik.rs
src/engine/core/tests/latin.rs
src/engine/core/tests/math.rs
src/frontends/qt5/src/input_context.cc
src/frontends/qt5/src/input_context.hpp

* Really fix [#425](https://github.com/Riey/kime/issues/425)
* Support nix `shell.nix`, `default.nix`

Release 2.3.3

---

default.nix
nix/deps.nix
shell.nix

Use clang for nix

---

.github/workflows/ci.yaml
Cargo.lock
default.nix
shell.nix
src/engine/backend/Cargo.toml
src/engine/cffi/Cargo.toml
src/engine/core/Cargo.toml
src/engine/core/src/config.rs

Update MSRV 1.51.0

---

src/engine/backend/Cargo.toml
src/engine/backends/emoji/Cargo.toml
src/engine/backends/hangul/Cargo.toml
src/engine/backends/hanja/Cargo.toml
src/engine/backends/latin/Cargo.toml
src/engine/backends/math/Cargo.toml
src/engine/capi/Cargo.toml
src/engine/cffi/Cargo.toml
src/engine/core/Cargo.toml
src/engine/dict/Cargo.toml
src/frontends/wayland/Cargo.toml
src/frontends/xim/Cargo.toml
src/tools/check/Cargo.toml
src/tools/indicator/Cargo.toml
src/tools/kime/Cargo.toml
src/tools/log/Cargo.toml
src/tools/run_dir/Cargo.toml
src/tools/version/Cargo.toml

Use GPL-3.0-or-later

---

Cargo.lock
default.nix
nix/deps.nix
shell.nix
src/engine/cffi/Cargo.toml

Set engine-capi to dependencies

---

docs/CHANGELOG.md
src/tools/kime/src/main.rs

Add kill flag in kime daemon

---

default.nix
docs/CHANGELOG.md
scripts/build.sh
scripts/install.sh
src/tools/check/src/main.rs

Don't install default config just provide as document file

Install docs

---

docs/CHANGELOG.md
src/engine/core/src/os.rs
src/tools/indicator/src/main.rs

Fix indicator doesn't change icon properly

---

docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md

Fix #462
Update outdated CONFIGURATION.md, and CONFIGURATION.ko.md.

Update outdated document (#462)

---

docs/CHANGELOG.md
src/frontends/xim/src/handler.rs

[XIM] Filter also key_release event

---

docs/CHANGELOG.md
src/tools/indicator/src/main.rs

Let indicator get icon_color in user config

---

docs/CONFIGURATION.ko.md

문서화되지 않은 `category_layout`을 삭제합니다.

---

docs/CHANGELOG.md
src/frontends/xim/src/main.rs

Don't exit xim when get `ServerError`

---

Cargo.lock
docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md
res/default_config.yaml
shell.nix
src/engine/capi/cbindgen-c.toml
src/engine/capi/cbindgen-cpp.toml
src/engine/capi/src/lib.rs
src/engine/cffi/src/lib.rs
src/engine/config/Cargo.toml
src/engine/config/src/lib.rs
src/engine/core/examples/make_config.rs
src/engine/core/src/config.rs
src/engine/core/src/lib.rs
src/tools/version/Cargo.toml
src/tools/version/src/lib.rs

* New `log` config
* Set specific level by command argument

Improve set log level

---

scripts/release-deb.sh

Use VERSION file instead git

---

docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md

Fix CONFIGURATION typo

---

docs/CONFIGURATION.ko.md

Correct a typo in CONFIGURATION.ko.md

---

.envrc

Use use flake

---

.github/workflows/ci.yaml

From upstream bug
https://github.com/cachix/install-nix-action/issues/83

Fix ci hash

---

docs/CHANGELOG.md
src/engine/backends/hangul/src/state.rs
src/engine/core/tests/sebeolsik_3_91.rs

Don't compose choseong when FlexibleComposeOrder is on

---

docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md

Fix invalid link in document

---

src/tools/candidate-window/src/main.rs

Resolve #546
This change is not listed on changelog because it's merged previous one

Support hanja candidate window hotkey

---

build-docker/ubuntu-21.10/Dockerfile

Add dockerfile for ubuntu-21.10

Add dockerfile for ubuntu-21.10

---

docs/CHANGELOG.md
src/frontends/gtk2/src/immodule.c

Fix incorrect CHANGELOG
Fix is_committing flag don't set FALSE again

Fix some wrong piece of #563

---

docs/CHANGELOG.md
src/frontends/gtk2/src/immodule.c

* Remove workaround patch from #536 #565
* Let handle preedit change in delayed event

Rework gtk event

---

build-docker/ubuntu-20.04/Dockerfile

Install libxcb-shape0-dev, libxcb-xfixes0-dev

---

docs/CHANGELOG.md
src/engine/dict/data/symbol_map.json

fix symbol name: downaroow -> downarrow

---

.github/workflows/ci.yaml
.vscode/settings.json
Cargo.lock
deny.toml
flake.lock
flake.nix
src/engine/backends/hangul/Cargo.toml
src/engine/backends/latin/Cargo.toml
src/engine/candidate/Cargo.toml
src/engine/capi/src/lib.rs
src/engine/cffi/Cargo.toml
src/engine/core/Cargo.toml
src/engine/core/src/config.rs
src/engine/dict/Cargo.toml
src/engine/dict/build.rs
src/frontends/wayland/Cargo.toml
src/frontends/xim/Cargo.toml
src/frontends/xim/src/handler.rs
src/frontends/xim/src/pe_window.rs
src/tools/candidate-window/Cargo.toml
src/tools/candidate-window/src/main.rs
src/tools/check/Cargo.toml
src/tools/indicator/Cargo.toml
src/tools/kime/Cargo.toml

Update lock files

---

deny.toml
docs/CHANGELOG.md
docs/CONFIGURATION.md
src/engine/backend/src/keycode.rs
src/engine/backends/hanja/src/lib.rs
src/engine/core/src/lib.rs
src/frontends/wayland/src/main.rs
src/frontends/xim/src/handler.rs
src/frontends/xim/src/main.rs
typos.toml

Fix typos and add config for typos-cli

---

docs/CHANGELOG.md
docs/CONFIGURATION.ko.md
docs/CONFIGURATION.md

Update configuration doc

---

src/engine/backends/hangul/src/lib.rs

Make `kime_engine_backend_hangul::Layout` public

---

src/engine/core/src/config.rs

Missing `cfg(unix)` branching for usage of `xdg` dependency

---

docs/CHANGELOG.md
src/engine/dict/data/symbol_map.json

add primes

---

Cargo.lock
src/engine/backend/Cargo.toml
src/engine/backends/emoji/Cargo.toml
src/engine/backends/hangul/Cargo.toml
src/engine/backends/hanja/Cargo.toml
src/engine/backends/latin/Cargo.toml
src/engine/backends/math/Cargo.toml
src/engine/candidate/Cargo.toml
src/engine/capi/Cargo.toml
src/engine/cffi/Cargo.toml
src/engine/config/Cargo.toml
src/engine/core/Cargo.toml
src/engine/dict/Cargo.toml
src/frontends/wayland/Cargo.toml
src/frontends/xim/Cargo.toml
src/tools/candidate-window/Cargo.toml
src/tools/check/Cargo.toml
src/tools/indicator/Cargo.toml
src/tools/kime/Cargo.toml
src/tools/log/Cargo.toml
src/tools/properties_writer/Cargo.toml
src/tools/run_dir/Cargo.toml
src/tools/version/Cargo.toml

Edition 2021

---

Cargo.lock
Cargo.toml
default.nix
flake.lock
flake.nix
nix/deps.nix
shell.nix
src/engine/backends/hangul/src/lib.rs
src/engine/cffi/Cargo.toml
src/engine/cffi/build.rs
src/engine/config/src/lib.rs

Bump bindgen and dependencies
Fix #675

Bump bindgen and dependencies
